### PR TITLE
Fix fish magic script on v0.19.0

### LINKED ISSUE #299: v0.19.0 magic errors out on fish
With the following line in my config.fish:

```fish
test -d "$HOME/.tea" && "$HOME/.tea/tea.xyz/v*/bin/tea" --magic --silent | source
```

I'm getting this error message when opening my term:

```
- (line 12): Missing end to balance this if statement
if ! tea true 2>&1 >/dev/null; then
^^
from sourcing file -
	called on line 12 of file ~/.config/fish/config.fish
from sourcing file ~/.config/fish/config.fish
	called during startup
source: Error while reading file '<stdin>'
```

I'd appreciate any ideas on this.

### PR DESCRIPTION
**Pull request by davdroman**
Fixes #299

### CODE REVIEW

**Review by jhheider — APPROVED** [review]
Good find.

**Comment by mxcl** [comment]
Sorry for this bug. We need CI for the magic somehow.

**Comment by davdroman** [comment]
Does current CI replicate installation on every shell? If so, we might be able to assert whether `fish --login` returns a status code != 0.

**Comment by jhheider** [comment]
It might be as simple as `for shell in fish zsh bash; do SHELL=$shell tea --magic | $shell; done`

**Comment by davdroman** [comment]
@jhheider doesn't seem to do the trick... 

image

**Comment by davdroman** [comment]
Oh nevermind it does, it's just the others returning 0 that override the status code. Returns 127 if I just run it for fish. 👌 

image

**Comment by jhheider** [comment]
Beautiful. I think that might be at least a first-pass test that there's no errors.

**Pull request merged**
