### PR TITLE
docs: document `deno task run` bug

### PR DESCRIPTION
**Pull request by vegerot**
docs: document `deno task run` bug

Summary:

reference issue #503 in comments

### CODE REVIEW

**Comment by mxcl** [comment]
Sorry I force pushed stuff and that probably led to this.

**Comment by vegerot** [comment]
@mxcl what?

**Comment by mxcl** [comment]
This is duplicate pr that you already opened and I merged.

**Comment by vegerot** [comment]
😁 no it's not.  I replaced the Deno issue with a Tea issue

**Pull request closed without merging**
