### PR TITLE
upload bins to www on release

### PR DESCRIPTION
**Pull request by jhheider**
Uploads binaries to `www` on release. Includes cleanup of some dead env and a lint fix that was failing.

### CODE REVIEW

**Comment by jhheider** [comment]
Ooooooooh. So close.
```sh
$ curl -L tea.xyz/(uname)/(uname -m) -o tea
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   105  100   105    0     0    195      0 --:--:-- --:--:-- --:--:--   196
100 74.4M  100 74.4M    0     0  28.1M      0  0:00:02  0:00:02 --:--:-- 43.6M
$ file tea
tea: Mach-O 64-bit executable arm64
$ chmod +x tea
$ ./tea --version
tea {{ steps.tea.outputs.version }}
```

**Comment by jhheider** [comment]
```sh
$ curl -L tea.xyz/(uname)/x86_64 -o tea; and file tea
tea: Mach-O 64-bit executable x86_64
$ curl -L tea.xyz/Linux/x86_64 -o tea; and file tea
tea: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, with debug_info, not stripped
$ curl -L tea.xyz/Linux/arm64 -o tea; and file tea
tea: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, with debug_info, not stripped
$ curl -L tea.xyz/Linux/aarch64 -o tea; and file tea
tea: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, with debug_info, not stripped
```

**Comment by jhheider** [comment]
resolves https://github.com/teaxyz/setup/issues/74

**Comment by mxcl** [comment]
`curl --compressed` sends `Accepts: gzip` but cloud front is strangely not sending the gzip’d content.

For `www.tea.xyz` we certainly should be compressing content, I'm guessing the CF settings are wrong. I'll open a ticket there.

**Pull request merged**
