### PR TITLE
docs: add social badges

### PR DESCRIPTION
**Pull request by mfts**
- twitter
- discord
- tea/cli version

### CODE REVIEW

**Comment by mxcl** [comment]
You didn't update your `.github` repo first. Colors have been updated.

**Comment by mxcl** [comment]
also you need to sign yo commits 
image

**Comment by mfts** [comment]
> You didn't update your .github repo first. Colors have been updated.

fixed

**Comment by mxcl** [comment]
You should fix your GPG signing. Ideally our script could diagnose why it doesn't work, which is more work but can be done.

**Pull request merged**
