### PR TITLE
Issue#324 - add test coverage

### LINKED ISSUE #324: enable code coverage
deno supports `--coverage`, then upload to whatever isn’t as terrible as codecov.io

### PR DESCRIPTION
**Pull request by ABevier**
Adding test coverage with coveralls.io.  Coverage is only counted for the ubuntu tests.  

fixes #324

### CODE REVIEW

**Comment by jhheider** [comment]
A different way to do it would be to add the coverage to the tests and use an if: key to only run it for one arm of the matrix.

**Comment by ABevier** [comment]
> A different way to do it would be to add the coverage to the tests and use an if: key to only run it for one arm of the matrix.

I considered that, but I decided against it because it seemed like it would make the job a little busy, but I can change it if you'd like.

**Comment by jhheider** [comment]
The main benefit I see is that it lets us keep the matrix working, instead of having one test elsewhere. Alternatively, running the test twice isn't the end of the world, either. I don't think there's any wrong answer here, just a matter of what people like.

**Comment by mxcl** [comment]
well, we should probably upload for both Mac and Linux anyway. We have platform specific pathways that we'll want to flag for coverage.

**Comment by jhheider** [comment]
Coveralls also produces [badges](https://github.com/jhheider/semverator/blob/618d6c95b5b6c95d1061c6175ebe1f4b0475929f/README.md?plain=1#L4), but seeing our 3% number might feel a little bad ;)

**Comment by jhheider** [comment]
> well, we should probably upload for both Mac and Linux anyway. We have platform specific pathways that we'll want to flag for coverage.

this is an interesting issue. i think coveralls is just last-upload-is-the-truth, so stomping one arch with the other isn't perfect. it'd be nice to mock platform in the tests, but i bet it's not feasible.

**Comment by ABevier** [comment]
> > well, we should probably upload for both Mac and Linux anyway. We have platform specific pathways that we'll want to flag for coverage.
> 
> this is an interesting issue. i think coveralls is just last-upload-is-the-truth, so stomping one arch with the other isn't perfect. it'd be nice to mock platform in the tests, but i bet it's not feasible.

They support sharding tests and then merging the results, I'm trying that out, but i'm not sure what's going to happen when the results stomp each other.

**Comment by ABevier** [comment]
Coveralls tracks the coverage of each job and appears to combine the results in sane way:

Screenshot 2023-02-28 at 6 30 38 PM

**Pull request merged**
