### PR TITLE
Handle `package@<version>` format

### LINKED ISSUE #514: `tea python@3` no longer works
How’d this break?

`utils/pkg.ts` can parse eg `node@16` correctly, we used to allow this on the command-line since users expect it and it stopped working.

### PR DESCRIPTION
**Pull request by JrGoodle**
fixes #514

probably a prettier way to do it, but this seems to get the job done

### CODE REVIEW

**Comment by mxcl** [comment]
can we demonstrate a usecase?

**Comment by JrGoodle** [comment]
from reading #514 I thought this was a regression.

but one example I can think of could be reading a `Brewfile` for package requirements. it doesn't look like that's implemented currently as one of the possible package sources, but it uses the `package@<version>` syntax.

**Comment by JrGoodle** [comment]
I started [hacking around to add support for Brewfiles](https://github.com/JrGoodle/cli/commit/20853a70edbe73a82351cd04797dfccb61e0c52e) and realized that's not really relevant to this one since it's just about cli arguments

and now I'm wondering if I misunderstood and you were you asking about adding another test?

**Comment by JrGoodle** [comment]
no worries, I just assumed from the way #514 was written that it was a recent regression. makes sense to hold off on it and keep the cli surface area smaller until there's actual demand

**Comment by mxcl** [comment]
I appreciate the PR, I am strict about changes without concrete justification tho. 🤝

**Pull request closed without merging**
