### PR TITLE
[ci] WSL2

### PR DESCRIPTION
**Pull request by ABevier**

### CODE REVIEW

**Comment by mxcl** [comment]
https://github.com/marketplace/actions/setup-wsl WSL2 not explicitly supported.

So we're going to need a self-hosted runner with Windows 10/11 with WSL2 preinstalled. @jhheider thoughts?

**Comment by jhheider** [comment]
Cheap windows box? Or an EC2 or Azure VPS. Assuming we add to pantry as well, dedicated hardware will give better return if we generate enough minutes.

**Comment by mxcl** [comment]
I was thinking of hosting it virtually on our existing runners, but I'm not fussed. If hardware is required then get waters to order it.

**Comment by jhheider** [comment]
we could run it virtually on the x86-64 box, but i worry about continuing to subdivide those resources. let me try and spin up a virtual runner and see what kind of timing we're looking at.

**Comment by mxcl** [comment]
WSL2 is identical to whatever linux you install inside it. So… this isn’t necessary IMO.

**Pull request closed without merging**
