### PR TITLE
Basic Path Sanitization

### PR DESCRIPTION
**Pull request by davidtai**
Do some basic path sanitization to prevent tmp escape attempts and to make `tea .` work properly by not trying to overwrite the temporary folder and fixing #130.

### CODE REVIEW

**Comment by mxcl** [comment]
Oh interesting. Well I think the proper fix is in `Path.ts` `join`. Which is mine and thus my bad code.

**Comment by mxcl** [comment]
I did wonder why `tea .` would error in some cases!

**Comment by davidtai** [comment]
> Oh interesting. Well I think the proper fix is in `Path.ts` `join`. Which is mine and thus my bad code.

There still needs to be a default filename for `tea .` sh that's set in here(called 'sh' in my fix).  I would normally just pull in a npm sanitization library to prevent any sort of escape but I'm not very familiar with deno's standard libraries.

**Comment by davidtai** [comment]
We should also pull all examples into the CI system to catch stuff like this.  I believe that @abitrolly started doing that in #129.

**Comment by mxcl** [comment]
Per our README `.` means “execute the default target in README.md”.

Perhaps this is dumb, what is your reaction?

**Comment by davidtai** [comment]
That is fine.  My point was directed at there still needs to be a filename appended to the tmp directory as most software will join a '.' as a no op and try and overwrite the directory, 

Since you are here I'd also like to point out that there is a related issue in #133 that is also a somewhat concerning user space execution security issue.  `tea .` is fine and convenient but we just have to make sure it handles all cases, if the markdown is empty:

```
# Getting Started

# sh

## hello
```

Then we try and execute `.` directly because there's an unreachable error message that seems like it should tell the user that there's no commands in `# Getting Started`.  The security aspect of this is what happens when you replace the harmless `.` with something less benign like execute `tea sh` which will open a shell (tested & confirmed).

**Pull request merged**
